// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.fovea1959.simple;
    

import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveSubsystemSpeedController0;
    public static SpeedController driveSubsystemSpeedController1;
    public static SpeedController driveSubsystemSpeedController2;
    public static SpeedController driveSubsystemSpeedController3;
    public static RobotDrive driveSubsystemRobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveSubsystemSpeedController0 = new Talon(0);
        LiveWindow.addActuator("DriveSubsystem", "Speed Controller 0", (Talon) driveSubsystemSpeedController0);
        
        driveSubsystemSpeedController1 = new Talon(1);
        LiveWindow.addActuator("DriveSubsystem", "Speed Controller 1", (Talon) driveSubsystemSpeedController1);
        
        driveSubsystemSpeedController2 = new Talon(2);
        LiveWindow.addActuator("DriveSubsystem", "Speed Controller 2", (Talon) driveSubsystemSpeedController2);
        
        driveSubsystemSpeedController3 = new Talon(3);
        LiveWindow.addActuator("DriveSubsystem", "Speed Controller 3", (Talon) driveSubsystemSpeedController3);
        
        driveSubsystemRobotDrive = new RobotDrive(driveSubsystemSpeedController0, driveSubsystemSpeedController1,
              driveSubsystemSpeedController2, driveSubsystemSpeedController3);
        
        driveSubsystemRobotDrive.setSafetyEnabled(true);
        driveSubsystemRobotDrive.setExpiration(0.1);
        driveSubsystemRobotDrive.setSensitivity(0.5);
        driveSubsystemRobotDrive.setMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
